### ISSUE TITLE
process exited with code 3221225477 (0xc0000005)

### ISSUE THREAD

**Issue by Pink-Punch** [panik4/RandomParadox#10]
when exporting a Vic3 map I get several errors about missing files in Vic3 that don't seem to exist, proceeding a crash. The Crash is persistent even when running the program on administrative mode
![image](https://github.com/user-attachments/assets/98ee87ca-3a6b-4b56-8747-59a0604cdbe7)

**Comment by panik4** [comment]
Could be a memory issue
Vic3 module at full resolution needs up to 9Gb of memory, and the step it crashes at is relatively memory hungry
Open the task manager while running it and observe memory usage. Close everything else you don't need

**Comment by panik4** [comment]
Closed due to no further activity
