### ISSUE TITLE
Executable not working on Windows 10

### ISSUE THREAD

**Issue by hypergolicSkunk** [panik4/RandomParadox#13]
I'm trying to run this on two different Win10 machines - on both, running the executable makes a command prompt open for a second, but nothing else happens.

I tried various compatibility modes, admin rights, etc. - no luck.

The previous RandomParadox runs fine.

Am I missing something?

**Comment by hypergolicSkunk** [comment]
Looks like I fixed it by 1. updating the .NET Framework, Visual C++ Redistributable, and 2. then running it as admin

**Comment by panik4** [comment]
Thanks for the report
It seems that one needs the newest 2022 Visual C++ Redistributable, I tested it myself just now
.NET framework should not be required, and running as admin also shouldn't
I'll consider creating an installer with the required Visual C++ Redistributable for the next version
