### ISSUE TITLE
HeightEdge works differently from WidthEdge

### ISSUE THREAD

**Issue by Hroppa** [panik4/RandomParadox#15]
When generating a Hoi4 heightmap, WidthEdge smoothly darkens the east and west edges of the map to avoid landmasses touching the edge.

However, HeightEdge imposes a flat height increase/decrease to all pixels above the set height threshold. The intended functionality is surely to impose a smooth drop-off, like WidthEdge?

**Comment by panik4** [comment]
You are indeed correct, thanks for the report.
Fixed it in Fwg, updated reference to it in commit https://github.com/panik4/RandomParadox/commit/faac1e43b248335014d5fde8d209849f12e0c676
![image](https://github.com/user-attachments/assets/ced393dc-f7b8-4cb4-8fdd-4810563fddb7)
