### ISSUE TITLE
Capitals Issue

### ISSUE THREAD

**Issue by Bruh2801** [panik4/RandomParadox#3]
Victory Points tend to be outside the states with victory points and as a result,the capital of countries is set incorrectly
![obraz](https://github.com/panik4/RandomParadox/assets/85746018/d65e11d4-bf03-4e7b-b66f-1cad552806e0)
as an example
another thing i've noticed is that the capital of some countries is set outside their territory in history/countries for example:
![obraz](https://github.com/panik4/RandomParadox/assets/85746018/613b2ab3-7644-4c06-bda8-a5d5ae2b5a0f)

**Comment by panik4** [comment]
Fixed for version 0.8.0
