### ISSUE TITLE
Issue with creating mod for Victoria 3

### ISSUE THREAD

**Issue by demetriuswork** [panik4/RandomParadox#8]
18:15:05:611 Configured paths seem to be messed up, check Victoria IIIModule.json
You can try fixing it yourself. Error is:
 create_directory: The system cannot find the path specified.
Press any key to continue . . .

**Comment by demetriuswork** [comment]
I got this when trying to go to the scenario tab.

**Comment by panik4** [comment]
Thanks for the report, I found the issue and fixed it. I will try to upload a patch soon

**Comment by panik4** [comment]
Fixed with release 0.7.1
